[package]
name = "geullint-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
morphology = ["dep:lindera"]

[dependencies]
aho-corasick.workspace = true
lindera = { version = "4.0.1", default-features = false, features = ["embed-ko-dic"], optional = true }
serde.workspace = true
serde_yaml = "0.9.34"
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
